import { Link } from "@tanstack/react-router";

export default function Footer() {
  const heading = { fontFamily: "'Inter', sans-serif", fontWeight: 500, fontSize: 13, textTransform: "uppercase" as const, letterSpacing: "0.1em", color: "var(--gold)", marginBottom: 12 };
  const body = { fontFamily: "'Inter', sans-serif", fontWeight: 300, fontSize: 12, color: "rgba(255,255,255,0.5)", lineHeight: 1.7 };
  const linkSt = { fontFamily: "'Inter', sans-serif", fontWeight: 300, fontSize: 14, color: "rgba(255,255,255,0.6)", display: "block", marginBottom: 8 };

  return (
    <footer style={{ background: "#1A1A1A", color: "#fff", padding: "64px 0 0", marginTop: 80 }}>
      <div style={{ maxWidth: 1280, margin: "0 auto", padding: "0 32px", display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 40 }}>
        <div>
          <div style={{ fontFamily: "'Playfair Display', serif", fontSize: 24, letterSpacing: "0.15em" }}>MAISON</div>
          <div style={{ fontFamily: "'Inter', sans-serif", fontWeight: 300, fontSize: 13, color: "rgba(255,255,255,0.5)", marginTop: 8 }}>
            Curated luxury. Rule-based discovery.
          </div>
        </div>
        <div>
          <div style={heading}>Navigate</div>
          <Link to="/" style={linkSt}>Home</Link>
          <Link to="/collections" style={linkSt}>Collections</Link>
          <Link to="/find-your-style" style={linkSt}>Find Your Style</Link>
        </div>
        <div>
          <div style={heading}>Research Study</div>
          <p style={body}>
            This site is part of a research study on AI-driven personalisation and brand loyalty. Recommendations are generated by manual preference selection only. No machine learning, behavioural tracking, or cookies are used.
          </p>
        </div>
        <div>
          <div style={heading}>Participate</div>
          <p style={body}>Share your experience by completing our short survey after browsing.</p>
          <a href="#" style={{ display: "inline-block", marginTop: 14, padding: "10px 18px", border: "1px solid var(--gold)", color: "var(--gold)", fontFamily: "'Inter', sans-serif", fontWeight: 500, fontSize: 12, textTransform: "uppercase", letterSpacing: "0.1em" }}>
            Take the Survey
          </a>
        </div>
      </div>
      <div style={{ marginTop: 48, padding: "20px 32px", borderTop: "1px solid rgba(255,255,255,0.1)", textAlign: "center", fontFamily: "'Inter', sans-serif", fontWeight: 300, fontSize: 11, color: "rgba(255,255,255,0.3)" }}>
        © 2025 MAISON Research Project. For academic purposes only.
      </div>
    </footer>
  );
}
